server:
  port: 8085


spring:
  application:
    name: production-planning
  cloud:
    nacos:
      discovery:
        # Nacos服务器地址，请根据实际情况修改(默认127.0.0.1:8848)
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8721

#sentinel
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
